### PR TITLE
fixes #58 and #59

### LINKED ISSUE #58: Exception in Context::__get doesnt provide the variable name
Instead of echoing the variable name, the string `$varname` is embedded in the exception message

### PR DESCRIPTION
**Pull request by MarcusSchwarz**

### CODE REVIEW

File: src/Context.php [hunk 1]
```diff
@@ -402,19 +406,19 @@ public function __get(string $varname)
...
             return constant($varname);
         }
 
-        if ($this->nothrow) {
+        if ($this->_nothrow) {
             return null;
         }
 
-        throw new Exception\VariableNotFoundException('Unable to find variable \'$varname\' in current scope');
+        throw new Exception\VariableNotFoundException("Unable to find variable \'$varname\' in current scope");
```
Comment (usox) [inline src/Context.php]: I think we don't need those backslashes any longer

**Review by usox — CHANGES_REQUESTED** [review]

**Review by usox — APPROVED** [review]
